### ISSUE TITLE
No date in results.csv

### ISSUE THREAD

**Issue by loicy** [For-The-Wolf/zwift-scrape#3]
Hey,

First of all, thank you for your work!

I tested the script which works but only for the "prime". I can't get any data in results & finished.

Is there anything in particular to do? Or has there been an update since on Zwiftpower?

Thanks for the feedback!

**Comment by For-The-Wolf** [comment]
Ooh cheers for the feedback - I'll take a look but most likely the website has changed slightly since I wrote the script, hopefully an easy fix :)

**Comment by For-The-Wolf** [comment]
Ahh yes, the need to log in with a Zwift account did not exist when I wrote the script - it looks like, once logged in, the rest of the website is the same, so the change should be simple

**Comment by loicy** [comment]
Hello,

Yes, when you run the script, it generates a Firefox window with the Zwift login, I think it takes this login page as the race results.

**Comment by For-The-Wolf** [comment]
I have pushed changes which should fix this issue for you. The WebDriver now waits for you to login before continuing, ideally I would add a method of storing your username/password so this occurs automatically but this was just a quick fix to get the script working again :)

The reason the data was empty before was that the scraper was running as soon as the score table loaded. However, the table takes some time to populate with data - the WebDriver now also waits for the table to become populated before continuing.
